import type { Category, Video } from './types';
import { MedicalIcon, TechIcon, DailyLifeIcon, BusinessIcon, EducationIcon, TravelIcon, FoodIcon, ArtIcon } from './components/icons';

export const CATEGORIES: Category[] = [
  { id: 'medical', name: 'Y tế', icon: MedicalIcon },
  { id: 'tech', name: 'Công nghệ', icon: TechIcon },
  { id: 'daily', name: 'Đời sống', icon: DailyLifeIcon },
  { id: 'business', name: 'Kinh doanh', icon: BusinessIcon },
  { id: 'education', name: 'Giáo dục', icon: EducationIcon },
  { id: 'travel', name: 'Du lịch', icon: TravelIcon },
  { id: 'food', name: 'Ẩm thực', icon: FoodIcon },
  { id: 'arts', name: 'Nghệ thuật', icon: ArtIcon },
];

export const VIDEOS: Video[] = [
  // Exam Preparation - Basic
  {
    id: 'sign_0001',
    gloss: 'KỲ THI THPT QUỐC GIA',
    variants: ['NATIONAL HIGH SCHOOL GRADUATION EXAM', 'EXAM'],
    description_vi: 'Bài học ngôn ngữ ký hiệu về kỳ thi THPT Quốc gia. Học từ vựng và lời chúc cho thí sinh: Thi, Bình tĩnh, Tự tin, Cố gắng. Một bài học động viên và hữu ích cho học sinh chuẩn bị thi cử.',
    categoryId: 'education',
    videoUrl: '/videoplayback.mp4',
    thumbnail: 'https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    duration_sec: 127,
    signer: {
      id: 'deaf_scdeaf_001',
      name: 'Thầy Thái Anh',
      bio: 'Giáo viên trung tâm ngôn ngữ kí hiệu Hà Nội',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=5',
    },
    domain_tags: ['giáo dục', 'kỳ thi', 'cơ bản', 'động viên'],
    level: 'basic',
    examples: [
      { text_vi: 'Chúc các sĩ tử thi thật tốt', sign_sequence: ['CHÚC', 'SĨ_TỬ', 'THI', 'TỐT'] },
      { text_vi: 'Hãy bình tĩnh và tự tin', sign_sequence: ['BÌNH_TĨNH', 'TỰ_TIN'] },
      { text_vi: 'Cố gắng lên các bạn', sign_sequence: ['CỐ_GẮNG', 'LÊN', 'BẠN'] },
    ],
    region: 'VN',
    created_at: '2025-11-20',
    license: 'cc-by-nc',
    verified_by: 'SCDeaf & Hội Người Điếc VN',
  },
  {
    id: 'sign_0002',
    gloss: 'Y TÁ',
    variants: ['NURSE', 'CAREGIVER'],
    description_vi: 'Người giúp đỡ bác sĩ chăm sóc bệnh nhân.',
    categoryId: 'medical',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 4,
    signer: {
      id: 'deaf_001',
      name: 'Thầy Thái Anh',
      bio: 'Giáo viên trung tâm ngôn ngữ kí hiệu Hà Nội',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=1',
    },
    domain_tags: ['y tế', 'cơ bản', 'nghề nghiệp'],
    level: 'basic',
    examples: [
      { text_vi: 'Y tá chăm sóc bệnh nhân', sign_sequence: ['Y TÁ', 'CHĂM_SÓC', 'BỆNH_NHÂN'] },
    ],
    region: 'VN',
    created_at: '2025-11-02',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },
  {
    id: 'sign_0003',
    gloss: 'BỆNH VIỆN',
    variants: ['HOSPITAL'],
    description_vi: 'Cơ sở khám chữa bệnh.',
    categoryId: 'medical',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 5,
    signer: {
      id: 'deaf_002',
      name: 'Trần B',
      bio: 'Chuyên gia NNKH, Trung tâm Giáo dục Người Điếc',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=2',
    },
    domain_tags: ['y tế', 'cơ bản'],
    level: 'basic',
    examples: [
      { text_vi: 'Đi bệnh viện khám sức khỏe', sign_sequence: ['ĐI', 'BỆNH_VIỆN', 'KHÁM', 'SỨC_KHỎE'] },
    ],
    region: 'VN',
    created_at: '2025-11-03',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },

  // Daily Life - Basic
  {
    id: 'sign_0005',
    gloss: 'YÊU',
    variants: ['LOVE', 'AFFECTION'],
    description_vi: 'Thể hiện tình cảm yêu thương, dùng trong giao tiếp thân mật hoặc gia đình.',
    categoryId: 'daily',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 3,
    signer: {
      id: 'deaf_001',
      name: 'Thầy Thái Anh',
      bio: 'Giáo viên trung tâm ngôn ngữ kí hiệu Hà Nội',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=1',
    },
    domain_tags: ['cảm xúc', 'cơ bản', 'gia đình'],
    level: 'basic',
    examples: [
      { text_vi: 'Mẹ yêu con', sign_sequence: ['MẸ', 'YÊU', 'CON'] },
    ],
    region: 'VN',
    created_at: '2025-11-05',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },
  {
    id: 'sign_0006',
    gloss: 'XIN CHÀO',
    variants: ['HELLO', 'HI', 'GREETING'],
    description_vi: 'Lời chào hỏi sơ bộ khi gặp người khác.',
    categoryId: 'daily',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 2,
    signer: {
      id: 'deaf_001',
      name: 'Thầy Thái Anh',
      bio: 'Giáo viên trung tâm ngôn ngữ kí hiệu Hà Nội',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=1',
    },
    domain_tags: ['cơ bản', 'chào hỏi'],
    level: 'basic',
    examples: [
      { text_vi: 'Xin chào, bạn khỏe không?', sign_sequence: ['XIN_CHÀO', 'BẠN', 'KHỎE'] },
    ],
    region: 'VN',
    created_at: '2025-11-06',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },

  // Tech - Intermediate
  {
    id: 'sign_0007',
    gloss: 'MÁY TÍNH',
    variants: ['COMPUTER', 'PC'],
    description_vi: 'Thiết bị điện tử dùng để xử lý thông tin và truyền tải dữ liệu.',
    categoryId: 'tech',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 4,
    signer: {
      id: 'deaf_003',
      name: 'Lê C',
      bio: 'Giáo viên NNKH chuyên ngành công nghệ',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=3',
    },
    domain_tags: ['công nghệ', 'trung cấp', 'vật dụng'],
    level: 'intermediate',
    examples: [
      { text_vi: 'Tôi sử dụng máy tính mỗi ngày', sign_sequence: ['TÔI', 'DÙNG', 'MÁY_TÍNH', 'HÀNG_NGÀY'] },
    ],
    region: 'VN',
    created_at: '2025-11-07',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },

  // Education - Intermediate
  {
    id: 'sign_0009',
    gloss: 'GIÁO VIÊN',
    variants: ['TEACHER', 'INSTRUCTOR'],
    description_vi: 'Người hướng dẫn, giảng dạy kiến thức cho học sinh.',
    categoryId: 'education',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 4,
    signer: {
      id: 'deaf_001',
      name: 'Thầy Thái Anh',
      bio: 'Giáo viên trung tâm ngôn ngữ kí hiệu Hà Nội',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=1',
    },
    domain_tags: ['giáo dục', 'trung cấp', 'nghề nghiệp'],
    level: 'intermediate',
    examples: [
      { text_vi: 'Giáo viên dạy chúng tôi tiếng Anh', sign_sequence: ['GIÁO_VIÊN', 'DẠY', 'CHÚNG_TÔI', 'TIẾNG_ANH'] },
    ],
    region: 'VN',
    created_at: '2025-11-09',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },
  {
    id: 'sign_0010',
    gloss: 'HỌC SINH',
    variants: ['STUDENT', 'LEARNER'],
    description_vi: 'Người đang theo học, tiếp nhận kiến thức từ giáo viên.',
    categoryId: 'education',
    videoUrl: '/videoplayback.mp4',
    duration_sec: 4,
    signer: {
      id: 'deaf_001',
      name: 'Thầy Thái Anh',
      bio: 'Giáo viên trung tâm ngôn ngữ kí hiệu Hà Nội',
      verified: true,
      avatar: 'https://i.pravatar.cc/48?img=1',
    },
    domain_tags: ['giáo dục', 'trung cấp', 'người'],
    level: 'intermediate',
    examples: [
      { text_vi: 'Học sinh chăm chỉ học bài', sign_sequence: ['HỌC_SINH', 'CHĂM_CHỈ', 'HỌC', 'BÀI'] },
    ],
    region: 'VN',
    created_at: '2025-11-10',
    license: 'cc-by-nc',
    verified_by: 'She+ & Hội Người Điếc HN',
  },
];
